---
version: '3.3'

services:
  wiki_reveal_gateway:
    image: nginx
    ports: ["8088:80"]
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./gateway/well-known:/www/data/.well-known:ro
    depends_on:
      - wiki_reveal_api
      - wiki_reveal_frontend

  wiki_reveal_api:
    build: .
    ports: ["8080"]

  wiki_reveal_frontend:
    build: ./tsclient
    ports: ["80"]
