---
version: '3.3'

services:
  wiki_reveal_gateway:
    build: ./gateway
    ports: ["8088:80"]
    restart: unless-stopped
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./gateway/well-known:/www/data/.well-known:ro
    depends_on:
      - wiki_reveal_api
      - wiki_reveal_frontend
    environment:
      - WR_ROOT

  wiki_reveal_api:
    build: .
    restart: unless-stopped
    ports: ["8080"]
    environment:
      - WR_LOGLEVEL
      - WR_SEED
      - WR_EPOCH
      - WR_ROOT

  wiki_reveal_frontend:
    build: ./tsclient
    restart: unless-stopped
    ports: ["80"]
    environment:
      - WR_ROOT
